#!/usr/bin/env bash

set -euo pipefail

: "${STRESS_SEED_TARGET_ROWS:=10000000}"
: "${STRESS_SEED_BATCH_SIZE:=10000}"
: "${STRESS_SEED_CLASSROOM_COUNT:=}"

export STRESS_SEED_TARGET_ROWS
export STRESS_SEED_BATCH_SIZE
export STRESS_SEED_CLASSROOM_COUNT

bun stress-seed.ts
